spring.application.name=discovery-service
server.port=8761

eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

# Keycloak - OAuth2 Resource Server (JWT)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9997/realms/ecom-ms-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9997/realms/ecom-ms-realm/protocol/openid-connect/certs
