spring.application.name=billing-service
server.port=8083
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:9999

# Keycloak - OAuth2 Resource Server (JWT)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9997/realms/ecom-ms-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9997/realms/ecom-ms-realm/protocol/openid-connect/certs
